<?php // catalog/includes/modules/shipping/translation_dutch_tntpost.php (5466)

// standaard functies wit
	 tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruikt TNT verzending', 'MODULE_SH_TNT_STATUS', 'True', 'Wil je klanten gebruik laten maken van TNTpost verzending?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");    	
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Jaar van ingevoerde tarieven', 'MODULE_SH_TNT_YEAR_RATES', 'Januari 2011', 'Voer het jaar in van de huidige ingevoerde tarieven (alleen ter informatie)', '6', '0', now())");   	
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, use_function, set_function, date_added) values ('Belastinggroep', 'MODULE_SH_TNT_TAX_CLASS', '0', 'Gerbuik de ingestelde belastinggroep voor de verzend vergoeding.', '6', '0', 'tep_get_tax_class_title', 'tep_cfg_pull_down_tax_classes(', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, use_function, set_function, date_added) values ('Verzend Zone', 'MODULE_SH_TNT_ZONE', '0', 'Als er een zone is geselecteerd, schakel dan alleen deze verzend methode in voor die zone.', '6', '0', 'tep_get_zone_class_title', 'tep_cfg_pull_down_zone_classes(', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Sorteer Volgorde', 'MODULE_SH_TNT_SORT_ORDER', '1', 'Sorteervolgorde op de pagina shipping.php tijdens afreken procedure.', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Rembours TNT comissie %', 'MODULE_SH_TNT_COD_COMMISSION', '0', 'TNTpost commissie percentage voor rembours-verzendingen', '6', '0', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Rembours TNT maximaal bedrag', 'MODULE_SH_TNT_COD_MAX_AMOUNT', '1000', 'TNTpost maximale bedrag voor rembours verzendingen.', '6', '0', now())");                
// administratie kosten rood
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Kosten vrij gewicht \'normaal\' brief-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_FREE_WGHT_LE_HO_CO', '50', 'Voer het maximale gewicht in als grens voor verzendingen vrij van verzendkosten', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Extra kosten brief verzending', 'MODULE_SH_TNT_LETTER_HANDLING', '0', 'Voer de extra kosten in voor het verzenden van brieven. (zoals enveloppe enz.)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Extra kosten boek pakket verzending', 'MODULE_SH_TNT_BOOK_HANDLING', '0', 'Voer de extra kosten in voor het verzenden van boek-pakketten (zoals doos enz.)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Extra kosten pakket verzending', 'MODULE_SH_TNT_PACKAGE_HANDLING', '0', 'Voer de extra kosten in voor het verzenden van pakket-verzendingen (zoals doos enz.)', '6', '0', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Extra kosten rembour verzending', 'MODULE_SH_TNT_COD_HANDLING', '0', 'Voer de extra kosten in voor het verzenden van rembours-verzendingen(zoals extra werk, risico, enz.)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'inklarings service\' voor plus pakket-verzendingen<br>alle landen', 'MODULE_SH_TNT_CS', 'True', 'Wil je klanten gebruik laten maken van inklarings service voor plus pakket-verzending alle landen?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
	 tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Priis \'inklarings service\'', 'MODULE_SH_TNT_PRICE_CS', '7.65', 'Prijs van inklarings service', '6', '0', now())");  
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'sealbag\' voor verzekerde verzendingen<br>alle landen', 'MODULE_SH_TNT_SB', 'True', 'Wil je klanten gebruik laten maken van een sealbag voor al je verzekerde verzendingen in alle landen?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Prijs \'sealbag\'', 'MODULE_SH_TNT_PRICE_SB', '2.85', 'Prijs van sealbag', '6', '0', now())");   	   	            
// brieven groen
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'normaal\' brief-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_NO_LE_HO_CO', 'True', 'Wil je klanten gebruik laten maken van normaal brief-verzendingen in jouw thuis land?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");    	
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'normaal\' brief-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_RATES_NO_LE_HO_CO', '20:0.46,50:0.92,100:1.38,250:1.84,500:2.30,2000:2.76', 'Tarieven normaal brief-verzendingen in jouw thuis land', '6', '0', now())");   	   	    
 	 tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'aangetekend\' brief-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_RE_LE_HO_CO', 'True', 'Wil je klanten gebruik laten maken van aangetekende brief-verzendingen in jouw thuis land (+ extra verzeker sevice )?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");    	
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'aangetekend\' brief en pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_RATES_RE_LE_HO_CO', '20:7.00,50:7.00,100:7.00,250:7.00,500:7.00,2000:8.05,5000:8.05,10000:8.05,20000:13.50,30000:13.50', 'Tarieven brief en pakket-verzendingen in jouw thuis land', '6', '0', now())");   	   	            
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven verzeker sevice \'aangetekend\' brief-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_RATES_REI_LE_HO_CO', '20:11.00,50:11.00,100:11.00,250:11.00,500:11.00,2000:11.00', 'Tarieven verzekersevice Tarieven brief-verzendingen in jouw thuis land', '6', '0', now())");   	   	                    
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'verzeker sevice\' brief-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_GA_LE_HO_CO', 'True', 'Wil je klanten gebruik laten maken van spoed brief en pakket-verzendingen in jouw thuis land (+ extra verzeker sevice)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'spoed\' brief en pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_RATES_GA_LE_HO_CO', '20:26.78,50:26.78,100:26.78,250:26.78,500:26.78,2000:29.75,5000:32.73,10000:44.63', 'Tarieven spoed brief en pakket-verzendingen in jouw thuis land (tarieven verzeker sevice zelfde als voor aangetekende brief-verzendingen)', '6', '0', now())");   	   	            
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik rembours brief-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_COD_LE_HO_CO', 'True', 'Wil je klanten gebruik laten maken van rembours brief-verzendingen in jouw thuis land (zelfde tarieven als rembours pakket-verzendingen)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())"); 	   	                    
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'normaal\' brief-verzendingen<br>Europa (Prioriteit)', 'MODULE_SH_TNT_NO_LE_EUR_PR', 'True', 'Wil je klanten gebruik laten maken van normaal brief-verzendingen binnen Europa (Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'normaal\' brief-verzendingen<br>Europa (Prioriteit)', 'MODULE_SH_TNT_RATES_NO_LE_EUR_PR', '20:59.90,50:59.90,100:59.90,250:59.90,500:59.90,2000:59.90', 'Tarieven normaal brief-verzendingen binnen Europa (Prioriteit)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'normaal\' brief-verzendingen<br>Europa (Standaard)', 'MODULE_SH_TNT_NO_LE_EUR_ST', 'True', 'Wil je klanten gebruik laten maken van normaal brief-verzendingen binnen Europa (Standaard) ?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'normaal\' brief-verzendingen<br>Europa (Standaard)', 'MODULE_SH_TNT_RATES_NO_LE_EUR_ST', '20:0.79,50:1.58,100:2.37,250:3.16,500:6.32,2000:8.69', 'Tarieven normaal brief-verzendingen binnen Europa (Standaard)', '6', '0', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'normaal\' brief-verzendingen<br>buiten Europa (Prioriteit)', 'MODULE_SH_TNT_NO_LE_WO_PR', 'True', 'Wil je klanten gebruik laten maken van normaal brief-verzendingen buiten Europa (Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())"); 
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'normaal\' brief-verzendingen<br>buiten Europa (Prioriteit)', 'MODULE_SH_TNT_RATES_NO_LE_WO_PR', '20:0.95,50:1.90,100:2.85,250:5.70,500:10.45,2000:16.15', 'Tarieven normaal brief-verzendingen buiten Europa (Prioriteit)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'aangetekend\' brief-verzendingen<br>Europa (Prioriteit)', 'MODULE_SH_TNT_RE_LE_EUR_PR', 'True', 'Wil je klanten gebruik laten maken van aangetekende brief-verzendingen binnen Europa (Prioriteit)(+ extra verzeker sevice, geen Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'aangetekend\' brief-verzendingen<br>Europa (Prioriteit)', 'MODULE_SH_TNT_RATES_RE_LE_EUR_PR', '20:9.48,50:9.48,100:9.48,250:9.48,500:9.48,2000:9.48', 'Tarieven aangetekende brief-verzendingen binnen Europa (Prioriteit)', '6', '0', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven verzeker sevice \'aangetekend\'<br>brief-verzendingen alle landen', 'MODULE_SH_TNT_RATES_REI_LE', '20:21.85,50:21.85,100:21.85,250:21.85,500:21.85,2000:21.85', 'Tarieven extra verzeker sevice aangetekende brief-verzendingen alle landen', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'aangetekend\' brief-verzendingen<br>buiten Europa (Prioriteit)', 'MODULE_SH_TNT_RE_LE_WO_PR', 'True', 'Wil je klanten gebruik laten maken van aangetekende brief-verzendingen buiten Europa (Prioriteit)(+ extra verzeker sevice, geen Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'aangetekend\' brief-verzendingen<br>buiten Europa (Prioriteit)', 'MODULE_SH_TNT_RATES_RE_LE_WO_PR', '20:16.15,50:16.15,100:16.15,250:16.15,500:16.15,2000:16.15', 'Tarieven aangetekende brief-verzendingen buiten Europa (Prioriteit)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'TraXity\' brief-verzendingen<br>voor sommige Europese landen', 'MODULE_SH_TNT_TRA_LE_EUR', 'True', 'Wil je klanten gebruik laten maken van TraXity brief-verzendingen voor sommige Europese landen?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'TraXity\' brief-verzendingen<br>voor sommige Europese landen', 'MODULE_SH_TNT_RATES_TRA_LE_EUR', '250:8.95,500:11.00,1000:14.20,2000:15.75', 'Tarieven TraXity brief-verzendingen voor sommige Europese landen', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'Spoed\' brief-verzendingen<br>overige Europese landen', 'MODULE_SH_TNT_EXP_LE_EUR', 'True', 'Wil je klanten gebruik laten maken van Spoed brief-verzendingen in overige Europese landen? (geen TraXity)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'Spoed\' brief-verzendingen<br>overige Europese landen', 'MODULE_SH_TNT_RATES_EXP_LE_EUR', '20:59.90,50:59.90,100:59.90,250:59.90,500:59.90,2000:59.90', 'Tarieven Spoed brief-verzendingen in overige Europese landen (geen TraXity)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'Spoed\' brief-verzendingen<br>buiten Europa', 'MODULE_SH_TNT_EXP_LE_WO', 'True', 'Wil je klanten gebruik laten maken van Spoed brief-verzendingen buiten Europa?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'Spoed\' brief-verzendingen<br>buiten Europa', 'MODULE_SH_TNT_RATES_EXP_LE_WO', '20:77.35,50:77.35,100:77.35,250:77.35,500:77.35,2000:77.35', 'Tarieven Spoed brief-verzendingen buiten Europa', '6', '0', now())");        
// boek pakketten bruin
	 tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik boek-verzendingen<br>Europa (Prioriteit)', 'MODULE_SH_TNT_BK_EUR_PR', 'True', 'Wil je klanten gebruik laten maken van boek-verzending binnen Europa (Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Minimum weight for all boek-verzendingen', 'MODULE_SH_TNT_BK_MIN_WGT', '2000', 'Minimaal gewicht van boek-verzendingen', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven boek-verzendingen<br>Europa (Prioriteit)', 'MODULE_SH_TNT_RATES_BK_EUR_PR', '3000:12.00,4000:12.95,5000:16.00', 'Tarieven boek-verzending binnen Europa (Prioriteit)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik boek-verzendingen<br>Europa (Standaard)', 'MODULE_SH_TNT_BK_EUR_ST', 'True', 'Wil je klanten gebruik laten maken van boek-verzending binnen Europa (Standaard)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven boek-verzendingen<br>Europa (Standaard)', 'MODULE_SH_TNT_RATES_BK_EUR_ST', '3000:9.65,4000:11.30,5000:13.80', 'Tarieven boek-verzending binnen Europa (Standaard)', '6', '0', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik boek-verzendingen<br>buiten Europa (Prioriteit)', 'MODULE_SH_TNT_BK_WO_PR', 'True', 'Wil je klanten gebruik laten maken van boek-verzending buiten Europa (Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven boek-verzendingen<br>buiten Europa (Prioriteit)', 'MODULE_SH_TNT_RATES_BK_WO_PR', '3000:23.90,4000:24.85,5000:27.30', 'Tarieven boek-verzending buiten Europa (Prioriteit)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik boek-verzendingen<br>buiten Europa (Standaard)', 'MODULE_SH_TNT_BK_WO_ST', 'True', 'Wil je klanten gebruik laten maken van boek-verzending buiten Europa (Standaard)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven boek-verzendingen<br>buiten Europa (Standaard)', 'MODULE_SH_TNT_RATES_BK_WO_ST', '3000:14.60,4000:17.40,5000:19.85', 'Tarieven boek-verzending buiten Europa (Standaard)', '6', '0', now())");        
// pakketten blauw
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'standaard\' pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_BA_PA_HO_CO', 'True', 'Wil je klanten gebruik laten maken van standaard pakket-verzending in jouw thuis land?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'standaard\' pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_RATES_BA_PA_HO_CO', '2000:6.75,5000:6.75,10000:6.75,20000:12.20,30000:12.20', 'Tarieven standaard pakket-verzendingen in jouw thuis land', '6', '0', now())");   	   	            
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'aangetekend\' pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_RE_PA_HO_CO', 'True', 'Wil je klanten gebruik laten maken van aangetekende pakket-verzending in jouw thuis land (+ extra verzeker sevice)(zelfde tarieven als aangetekende brief-verzendingen)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");    	
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'spoed\' pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_GA_PA_HO_CO', 'True', 'Wil je klanten gebruik laten maken van verzeker sevice pakket-verzending in jouw thuis land (+ extra verzeker sevice)(zelfde tarieven als verzeker sevice brief-verzendingen)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");      
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'verzekerservice\' pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_CE_PA_HO_CO', 'True', 'Wil je klanten gebruik laten maken van zeker pakket-verzending in jouw thuis land?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'verzekerservice\' pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_RATES_CE_PA_HO_CO', '2000:13.55,5000:13.55,10000:13.55,20000:19.00,30000:19.00', 'Tarieven zeker pakket-verzendingen in jouw thuis land', '6', '0', now())");   	   	            
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik rembours pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_COD_PA_HO_CO', 'True', 'Wil je klanten gebruik laten maken van Rembours pakket-verzending in jouw thuis land?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven rembour pakket-verzendingen&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_RATES_COD_PA_HO_CO', '2000:15.83,5000:15.83,10000:15.83,20000:20.00,30000:20.00', 'Tarieven rembours pakket-verzending in jouw thuis land', '6', '0', now())");   	   	            
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik meerdere spoed pakketten&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_MLT_INS_HO_CO', 'True', 'Wil je klanten gebruik laten maken van meerdere spoed pakket-verzending in jouw thuis land (boven maximale gewicht)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik meerdere \'verzekerservice\' pakketten&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_MLT_CE_HO_CO', 'True', 'Wil je klanten gebruik laten maken van meerdere verzekerservice pakket-verzending in jouw thuis land (boven maximale gewicht)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");     
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik meerdere rembours pakketten&nbsp;<font color=red>N</font><font color=grey>E</font><font color=blue>D</font>', 'MODULE_SH_TNT_MLT_COD_HO_CO', 'True', 'Wil je klanten gebruik laten maken van meerdere rembours pakket-verzending in jouw thuis land (boven maximale gewicht)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik internationaal \'standaard\' pakket-verzendingen<br>Europa (Prioriteit)', 'MODULE_SH_TNT_BA_PA_EUR_PR', 'True', 'Wil je klanten gebruik laten maken van internationaal standaard pakket-verzending binnen Europa (Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven internationaal \'standaard\' pakket-verzendingen<br>Europa (Prioriteit)', 'MODULE_SH_TNT_RATES_BA_PA_EUR_PR', '2000:18.50,5000:25.00,10000:31.00,20000:40.00,30000:47.60', 'Tarieven internationaal standaard pakket-verzending binnen Europa (Prioriteit)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik internationaal \'standaard\' pakket-verzendingen<br>Europa (Standaard)', 'MODULE_SH_TNT_BA_PA_EUR_ST', 'True', 'Wil je klanten gebruik laten maken van internationaal standaard pakket-verzending binnen Europa (Standaard)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven internationaal \'standaard\' pakket-verzendingen<br>Europa (Standaard)', 'MODULE_SH_TNT_RATES_BA_PA_EUR_ST', '2000:13.00,5000:19.50,10000:25.00,20000:34.00,30000:40.46', 'Tarieven internationaal standaard pakket-verzending binnen Europa (Standaard)', '6', '0', now())");       
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik internationaal \'standaard\' pakket-verzendingen<br>buiten Europa (Prioriteit)', 'MODULE_SH_TNT_BA_PA_WO_PR', 'True', 'Wil je klanten gebruik laten maken van internationaal standaard pakket-verzending buiten Europa (Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven internationaal \'standaard\' pakket-verzendingen<br>buiten Europa (Prioriteit)', 'MODULE_SH_TNT_RATES_BA_PA_WO_PR', '2000:24.30,5000:34.30,10000:58.30,20000:105.30', 'Tarieven internationaal standaard pakket-verzending buiten Europa (Prioriteit)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik internationaal \'standaard\' pakket-verzendingen<br>buiten Europa (Standaard)', 'MODULE_SH_TNT_BA_PA_WO_ST', 'True', 'Wil je klanten gebruik laten maken van internationaal standaard pakket-verzending buiten Europa (Standaard)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven internationaal \'standaard\' pakket-verzendingen<br>buiten Europa (Standaard)', 'MODULE_SH_TNT_RATES_BA_PA_WO_ST', '2000:24.30,5000:34.30,10000:58.30,20000:105.30', 'Tarieven internationaal standaard pakket-verzending buiten Europa (Standaard)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik internationaal \'plus\' pakket-verzendingen<br>EU (Prioriteit)', 'MODULE_SH_TNT_PL_PA_EU_PR', 'True', 'Wil je klanten gebruik laten maken van internationaal plus pakket-verzending binnen de Europese Union (Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'aangetekend\' pakket-verzendingen<br>Europa (Prioriteit)', 'MODULE_SH_TNT_RE_PA_EUR_PR', 'True', 'Wil je klanten gebruik laten maken van registered pakket-verzending binnen Europa (Prioriteit)(+ extra verzeker sevice, geen Prioriteit)(zelfde tarieven als aangetekende brief-verzendingen)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'aangetekend\' pakket-verzendingen<br>buiten Europa (Prioriteit)', 'MODULE_SH_TNT_RE_PA_WO_PR', 'True', 'Wil je klanten gebruik laten maken van registered pakket-verzending buiten Europa (Prioriteit)(+ extra verzeker sevice, geen Prioriteit)(zelfde tarieven als aangetekende brief-verzendingen)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'TraXity\' pakket-verzendingen<br>voor sommige Europese landen', 'MODULE_SH_TNT_TRA_PA_EUR', 'True', 'Wil je klanten gebruik laten maken van TraXity pakket-verzending voor sommige Europese landen (zelfde tarieven als TraXity brief-verzendingen)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'Spoed\' pakket-verzendingen<br>overige Europese landen', 'MODULE_SH_TNT_EXP_PA_EUR', 'True', 'Wil je klanten gebruik laten maken van Spoed pakket-verzending in overige Europese landen (no TraXity)(zelfde tarieven als Spoed brief-verzendingen)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik \'Spoed\' pakket-verzendingen<br>buiten Europa', 'MODULE_SH_TNT_EXP_PA_WO', 'True', 'Wil je klanten gebruik laten maken van Spoed pakket-verzending buiten Europa (zelfde tarieven als Spoed brief-verzendingen)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
// zone rates paars
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'ZONE 1\' internationaal \'plus\' pakket-verzendingen<br>EU (Prioriteit)', 'MODULE_SH_TNT_RATES_1_PL_PA_EU_PR', '2000:13.00,5000:19.50,10000:25.00,20000:34.00,30000:40.46', 'Tarieven zone 1 internationaal plus verzending binnen de Europese Unie (Prioriteit)', '6', '0', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'ZONE 2\' internationaal \'plus\' pakket-verzendingen<br>EU (Prioriteit)', 'MODULE_SH_TNT_RATES_2_PL_PA_EU_PR', '2000:18.50,5000:25.00,10000:31.00,20000:40.00,30000:47.60', 'Tarieven zone 2 internationaal plus verzending binnen de Europese Unie (Prioriteit)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'ZONE 3\' internationaal \'plus\' pakket-verzendingen<br>EU (Prioriteit)', 'MODULE_SH_TNT_RATES_3_PL_PA_EU_PR', '2000:19.30,5000:26.30,10000:32.30,20000:42.30', 'Tarieven zone 3 internationaal plus verzending binnen de Europese Unie (Prioriteit)', '6', '0', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik internationaal \'plus\' pakket-verzendingen<br>buiten EU (Prioriteit)', 'MODULE_SH_TNT_PL_PA_WO_PR', 'True', 'Wil je klanten gebruik laten maken van internationaal plus pakket-verzending buiten de Europese Unie (Prioriteit)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'ZONE 4\' internationaal \'plus\' pakket-verzendingen<br>buiten EU (Prioriteit)', 'MODULE_SH_TNT_RATES_4_PL_PA_WO_PR', '2000:24.30,5000:34.30,10000:58.30,20000:105.30', 'Tarieven zone 4 internationaal plus pakket-verzending buiten de Europese Unie (Prioriteit)', '6', '0', now())");        
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'ZONE 5\' internationaal \'plus\' pakket-verzendingen<br>buiten EU (Prioriteit)', 'MODULE_SH_TNT_RATES_5_PL_PA_WO_PR', '2000:24.30,5000:34.30,10000:58.30,20000:105.30', 'Tarieven zone 5 internationaal plus pakket-verzending buiten de Europese Unie (Prioriteit)', '6', '0', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik internationaal \'plus\' pakket-verzendingen<br>buiten EU (Economy)', 'MODULE_SH_TNT_PL_PA_WO_EC', 'True', 'Wil je klanten gebruik laten maken van internationaal plus pakket-verzending buiten de Europese Unie (Economy; over zee)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Tarieven \'ZONE 5\' internationaal \'plus\' pakket-verzendingen<br>buiten EU (Economy)', 'MODULE_SH_TNT_RATES_5_PL_PA_WO_EC', '2000:24.30,5000:34.30,10000:58.30,20000:105.30', 'Tarieven zone 5 internationaal plus pakket-verzending buiten de Europese Unie (Economy; over zee)', '6', '0', now())");
// multiple grijs
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik meerdere verzekerde pakketten<br>buiten thuis land', 'MODULE_SH_TNT_MLT_INS_WO', 'True', 'Wil je klanten gebruik laten maken van meerdere verzekerde pakket-verzending in jouw thuis land (boven maximale gewicht)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
     tep_db_query("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Gebruik meerdere \'plus\' pakketten<br>buiten thuis land', 'MODULE_SH_TNT_MLT_PL_WO', 'True', 'Wil je klanten gebruik laten maken van meerdere plus pakket-verzending buiten jouw thuis land (boven maximale gewicht)?', '6', '0', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");     
?>
